// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package models

// Model of the Audio Journal.
// This stores the string for Title.
// This stores the binary for Audio file.
type Journal struct {
	// Set to true if the user's email has been verified.
	Audio string `json:"audio"`
	Id    *int   `json:"id,omitempty"`
	Title string `json:"title"`
}
