// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /journal)
	GetJournal(ctx echo.Context) error
	// Create New Journal
	// (POST /journal)
	PostJournal(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetJournal converts echo context to params.
func (w *ServerInterfaceWrapper) GetJournal(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetJournal(ctx)
	return err
}

// PostJournal converts echo context to params.
func (w *ServerInterfaceWrapper) PostJournal(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostJournal(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/journal", wrapper.GetJournal)
	router.POST(baseURL+"/journal", wrapper.PostJournal)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/6xUUY/bNgz+KwI3YC9unGv30PNe1nbDcBu6Fd31qbsHnczEymRJI+lcg0P++0DZiZNL",
	"Bwxb32yRFD9+/PQ9gkt9ThGjMDSPwK7D3pbPn9NA0Qb9bJEd+Sw+RWjgbWoxmLQy0qF5NbQ+mSl38Ue8",
	"7TwblkTIJc5CPq7NKpG59RLwMyn3PlralZTxtpUPuIAK8JPtc0CG5uNdBZlSRhKPBZ3VzEtsv6MYSUZo",
	"QONHhAMjfcMGe+uD6Sybe8Rotkh+5bHVPqtEvRVoYEQCFcguIzQwgod9Bb7VXtOxj4JrJD0XnekkdKjY",
	"V0D41+AJW2g+TmnVhPruWHck+dgy3W/QCez1Bh9XZUSXolgn+lmmgAZCotalFunq+nr5/VpPFy71UEG0",
	"PT5NUKTnPJUd9N5RYqStd3hYiI2tIRTyuEU+3y5/Z9C6zmzG38KlNWWSUmajsczJeSvYGntcJVQQvMPI",
	"hagJ39ubW6hgIB2mE8nc1HXKGDkN5HCRaF1PRVxr7r4CHvpe19PAa8vemTfvP/xwopoDSpjZLYGZ4i0S",
	"j+NfLQon2tBmDw28WOhRBdlKV/RVb2b5r1EulXYgKRiXQkCnx/ooDjBUWCpYq4GbFhr4CWXGoupAltep",
	"3R1WjLG06YcgPluSWnX5rLVi55d5IrVZKUVsnJOSpQnPl8snd9qcg3cFSr1hxX96oRfsS+HXhCto4Kt6",
	"NoV6coT6AH1/lKolsrtRqefU/PbLeJoTf4a4N4RW0FgT8eGgpUuy3iX+Mmz9q5kuZ9D+xT4iOmQuBuUx",
	"tFwUV5zv3Y1ajTsdR71mAf93H/8R8gdGMiO7rWJ4vrz6J/ZL/NsR1hNz98xq2O8n9zI3cbRHDZei68ui",
	"H4u3vgqEtt2ZW/snxmKB84udlv4rPpizCdR9kNThH0/MoKnrkJwNXWJpXiyXS9jfVfDpGUvKwa+7wqFa",
	"MnQb9/Ihu5dhm2gF+/3fAQAA///KN42K0AYAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
